#!/bin/bash

A="aggregate(opraqte, quote_best(quote) as quote, exch, instrument_id, day, ms)"

B="redimension($A,
     <quote:quote null>
     [instrument_id=0:*,100,0,day=0:*,1,0,ms=0:86399999,600000,0],
     quote_accumulate(quote) as quote)"

C="cumulate($B, quote_best(quote) as nbbo, ms)"

iquery -aq "$C"
